version: '3.7'

services:
    chroma:
        image: chromadb/chroma:latest
        restart: always
        healthcheck: 
          test: curl localhost:8000/api/v1/heartbeat || exit 1
          interval: 10s
          retries: 2
          start_period: 5s
          timeout: 10s
        volumes:
          - chroma_data:/chroma/chroma
        ports:
          - 8000:8000
        networks:
          ragnet:

    search_engine:
        build:
            context: ./search_engine
            dockerfile: Dockerfile
        restart: always
        depends_on:
          chroma:
            condition: service_healthy
        ports:
          - 1337:1337
        networks:
            ragnet:

    tg_bot:
        build:
            context: ./tg_bot
            dockerfile: Dockerfile
        restart: always
        depends_on:
          chroma:
            condition: service_healthy
          search_engine:
            condition: service_started
        networks:
            ragnet:

volumes:
  chroma_data:

networks:
  ragnet:
    driver: bridge
    name: ragnet